import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Report } from "@/lib/schemas";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 4, color: "#1e293b" },
  subheader: { fontSize: 10, color: "#64748b", marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", marginBottom: 6, color: "#0f172a" },
  row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  grade: { fontSize: 14, fontFamily: "Helvetica-Bold", padding: "4 12", borderRadius: 4 },
  score: { fontSize: 24, fontFamily: "Helvetica-Bold" },
  scoreLabel: { fontSize: 11, color: "#64748b" },
  body: { fontSize: 10, lineHeight: 1.5, color: "#334155" },
  redFlag: { fontSize: 10, color: "#991b1b", marginBottom: 4 },
  dimHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4, marginTop: 12, paddingTop: 8, borderTop: "1 solid #e2e8f0" },
  dimTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#0f172a" },
  dimScore: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#0f172a" },
  dimMeta: { fontSize: 9, color: "#64748b", marginBottom: 4 },
  quickFix: { fontSize: 9, color: "#065f46", backgroundColor: "#ecfdf5", padding: 6, borderRadius: 4, marginTop: 4 },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

function gradeColor(grade: string) {
  switch (grade) {
    case "Elite": return { bg: "#d1fae5", text: "#065f46" };
    case "Strong": return { bg: "#dbeafe", text: "#1e40af" };
    case "Inconsistent": return { bg: "#fef3c7", text: "#92400e" };
    case "At Risk": return { bg: "#ffedd5", text: "#9a3412" };
    case "Fail": return { bg: "#fee2e2", text: "#991b1b" };
    default: return { bg: "#f1f5f9", text: "#334155" };
  }
}

export function EvaluationPDF({ report, runId }: { report: Report; runId: string }) {
  const color = gradeColor(report.grade);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Halden Method — Call Evaluation</Text>
        <Text style={styles.subheader}>Run ID: {runId}</Text>

        <View style={styles.row}>
          <View><Text style={[styles.grade, { backgroundColor: color.bg, color: color.text }]}>{report.grade}</Text></View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={styles.score}>{report.total_score}</Text>
            <Text style={styles.scoreLabel}>out of 100</Text>
            {report.max_possible < 100 && <Text style={styles.scoreLabel}>Normalized from {report.max_possible} pts</Text>}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>The One Thing</Text>
          <Text style={styles.body}>{report.one_thing.dimension}</Text>
          <Text style={styles.body}>{report.one_thing.description}</Text>
          <Text style={[styles.body, { marginTop: 4 }]}>Potential gain: +{report.one_thing.point_gain} points (would score {report.one_thing.new_total})</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Brief to Coach</Text>
          <Text style={styles.body}>{report.brief}</Text>
        </View>

        {report.red_flags.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Red Flags</Text>
            {report.red_flags.map((flag, i) => <Text key={i} style={styles.redFlag}>• {flag}</Text>)}
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Dimension Breakdown</Text>
          {report.dimensions.map((dim) => (
            <View key={dim.id}>
              <View style={styles.dimHeader}>
                <Text style={styles.dimTitle}>{dim.id} — {dim.name}</Text>
                <Text style={styles.dimScore}>{dim.disabled ? "N/A" : `${dim.score} / ${dim.max_score}`}</Text>
              </View>
              {dim.disabled ? (
                <Text style={styles.dimMeta}>{dim.disabled_reason}</Text>
              ) : (
                <>
                  <Text style={styles.dimMeta}>Band: {dim.band}</Text>
                  <Text style={styles.body}>{dim.reasoning}</Text>
                  <Text style={styles.quickFix}>Quick fix: {dim.quick_fix}</Text>
                  {dim.capped_reason && <Text style={[styles.body, { color: "#92400e", marginTop: 4 }]}>Cap: {dim.capped_reason}</Text>}
                </>
              )}
            </View>
          ))}
        </View>

        <Text style={styles.footer}>Generated by BeaverMind AI Evaluator • {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}
